### ISSUE TITLE
Compatibility with Angular 2

### ISSUE THREAD

**Issue by aikeru** [ngReact/ngReact#101]
Is compatibility with angular 2 in the works? :) if so, perhaps it could be tracked with this issue.

**Comment by kasperp** [comment]
@aikeru no there is nothing in the works, but lets leave this issue open for this discussion.

**Comment by aikeru** [comment]
@kasperp I took an initial stab at this myself at HTTPS://github.com/aikeru/ReactEverything the relevant source is in /demo/Angular2.ReactComponent.js (an ES5 Angular 2 component).

I am new to Angular 2 (who isn't haha) and this is just a quick stab at it but it is functional in that it renders and updates when props are updated.

If you took a PR or something for Angular 2 functionality (which would be a component and not a directive I guess :)) what might that look like in your repo/etc?

**Comment by kasperp** [comment]
yeah - those are good questions. Too be honest I haven't really dived into angular 2. So any suggestions on what angular2/react interop would mean are welcome.

**Comment by kasperp** [comment]
Closed due to ina, feel free to reopen

**Comment by evenh** [comment]
Seems like this is worth a read: http://www.syntaxsuccess.com/viewarticle/integrating-react-with-angular-2.0
