### ISSUE TITLE
ngReact executes function props

### ISSUE THREAD

**Issue by ghost** [ngReact/ngReact#114]
https://github.com/davidchang/ngReact/blame/master/ngReact.js#L218

This line seems to immediately execute any functions that are passed in as props. Is there a way to fix this?

**Comment by jjstrat3** [comment]
I've been encountering this as well.  It certain scenarios it manifests in "$digest already in progress" errors.  Not sure what other way there is other than $eval to ensure scope gets applied for the props?

**Comment by kasperp** [comment]
Thanks for reporting this. I'm also unsure about how to fix this, any ideas would be welcome.

**Comment by cypherq** [comment]
@kasperp isn't enough to run it immediately in next digest cycle?

```javascript
$timeout(function() {
  // anything you want can go here and will safely be run on the next digest.
})
```

**Comment by aabenoja** [comment]
@cypherq It would be cleaner (and less hacky) to use `$scope.$evalAsync()` to schedule the evaluation for the next cycle. While this certainly solves the digest in progress errors, I don't think this necessarily solves @danmartinez101's issue, which sounds like he's trying to pass a callback to his angular component much like you would in `ngClick`.

**Comment by kasperp** [comment]
Anyone want to attempt a pull request for this ?
