### ISSUE TITLE
Travis Testing

### ISSUE THREAD

**Issue by aabenoja** [ngReact/ngReact#119]
As it stands `ngReact` tests against `0.10`, `0.11`, `0.12` and `iojs`. I'm putting together a PR to test against `4.x` and later. While the tests are pretty fast I'm fairly hesitant to increase the number of environments. So I propose a couple of changes.

* Drop `0.11` - that was an experimental branch that lead up to `0.12` (from what I recall), so I see very little reason to continue supporting it.
* Support `4.x.x` - v4 is LTS, so this isn't going away anytime soon.
* Support `node` - v5 was released recently, so we may as well test against the latest node releases.

I'm fairly certain `0.10` and `0.12` are getting used in a lot of places still. The only one I'm uncertain of is `iojs`. With v4 (and v5) released I don't really see a need to continue it's support, but that's just my opinion on the matter.

**Comment by kasperp** [comment]
:+1: I agree with that. lets just test on >= 4

**Comment by kasperp** [comment]
And thanks again for you efforts.

**Comment by aabenoja** [comment]
I could probably sneak this in with #118, especially with the `devDependencies` changes I made to work better in `npm@3.x`.

**Comment by kasperp** [comment]
Go for it
