### ISSUE TITLE
watch-depth attribute types explained

### ISSUE THREAD

**Issue by 3v3r3tt** [ngReact/ngReact#124]
This is more of a question than an issue, but was wondering if you could further expand upon the watch-depth attribute types mentioned in the readme?

http://stackoverflow.com/questions/33833634/ngreact-watch-depth-attribute-types-explained

**Comment by kasperp** [comment]
Thanks for raising this. Your right we could expand on the README with a better description. Until that happens you can look at the pull-request #48 for this feature.

**Comment by 3v3r3tt** [comment]
Thanks! Really appreciate the speedy response and awesome library!

*Paul*
