### ISSUE TITLE
hot module replacement fails

### ISSUE THREAD

**Issue by qinyadong** [ngReact/ngReact#132]
look at the example 'es6-tests-webpack' 
![image](https://cloud.githubusercontent.com/assets/13127059/12166483/3d24ce54-b561-11e5-8f7a-d00b4e5e3f37.png)

**Comment by kasperp** [comment]
@qinyadong do you have a suggestion for a fix?

**Comment by kasperp** [comment]
closed due to inactivity,  feel free to reopen
