### ISSUE TITLE
ngReact becomes an Angular to React conversion tool 

### ISSUE THREAD

**Issue by MRHarrison** [ngReact/ngReact#136]
I see there is discussion for ngReact in Angular2, but I'm not too excited about what Angular2 has to offer.  I have been persuaded to think that React is a better solution than Angular.  This is more a of a discussion than and issue.  But it would be great to have a tool that will allow for **incremental changes** of an Angular app to React.  There would be a lot of package choices to make, i.e. react router, data handler, etc..  But I think a lot of people would want to get out of the Angular eco system.

**Comment by kasperp** [comment]
@MRHarrison a similar discussion happen on #140, was that also what you are looking for ?

**Comment by MRHarrison** [comment]
Yeah, thanks!
