### ISSUE TITLE
cannot find react component

### ISSUE THREAD

**Issue by gusbueno** [ngReact/ngReact#137]
This is my problem(with example code):

http://stackoverflow.com/questions/35256295/cannot-find-react-component-logincomponent-ng-react

What can I do?

**Comment by Edgar160** [comment]
I think you may need to check this https://github.com/ngReact/ngReact#jsx-transformation-in-the-browser

**Comment by kasperp** [comment]
@gusbueno did @Edgar160 suggestion help you move forward ?

**Comment by gusbueno** [comment]
@kasperp @Edgar160 yes! thank you very much!
