### ISSUE TITLE
Allow '@' scope binding

### ISSUE THREAD

**Issue by whistler** [ngReact/ngReact#138]
When using `reactDirective` to wrap a React Component it would be nice to have more control over the type of binding used per attribute. In specific I want to use the '@' type scope for Angular directives. Assuming `myComponent` is a directive generated using `reactDirective`, the following code looks for a scope variable named `value1` and passes its value to the React Component.

    <my-component attr1="value1" attr2="value2">

What I would like instead would be a way to pass a string to the React Component directly from the Angular view template for a certain attribute. Essentially some way of specify that `attr1` should be treated as the string `"value1"` and not the value of `$scope.value1`. 

I can achieve this using the following syntax but when porting Angular directives into React Components it can be important to keep the API of a component the same as before.

    <my-component attr1="'value1'" attr2="value2">

**Comment by kasperp** [comment]
Thanks for the issue.  I'm a not sure I think it is worth the effort, give the fairly easy work around.
