### ISSUE TITLE
React to Angular?

### ISSUE THREAD

**Issue by amcdnl** [ngReact/ngReact#140]
I have a Angular 1.x app and I'm wanting to migrate it from Angular to React completely. I'm already using this component in a few different areas of my app ( great work btw ).

So my thoughts on how to accomplish something like this:

- React is at the top level, using a react router
- React component to wrap Angular ( reverse of this project )

Would love to hear your feedback and see if the reverse of this would be a good addition for this library ( if even possible ).

**Comment by tolyo** [comment]
Currently in the process of a similar migration. The biggest hurdle for me has been migrating an angular app to ES6, which in the context of learning React/Flux/Redux is overwhelming. If you want to do a complete migration, you might as well do a complete rewrite from scratch. Otherwise, my route has been the way towards ES6 with ngReact serving nicelyl when Angular underperformed.

**Comment by amcdnl** [comment]
I'm already using ES6/7 all over with es6 modules too. Just need to get the hooks setup for the transition.

Writing from scratch is not a option for me, my app is quite big and complex but incremental updates are tolerable

**Comment by kasperp** [comment]
For an incremental approach, I have done a migration "inside-out", so one "page/component" at a time (using ngReact as glue). Leaving the routing to angular until most/all views was rendered with React and we were ready to do a full migration.

For angular services, we separated the functionality from the angular service definition. Refactored the functionality to be independent from angular (replacing `angular.forEach` etc.). This way we could use "the services" both in the old angular code and in the new react components. 

For using Angular inside React you can look at #120

**Comment by amcdnl** [comment]
@kasperp Thanks for the feedback! We should collab on a blog post :)

**Comment by MRHarrison** [comment]
Make sure to include that blog post in the README, I think a lot of people looking to use ngReact are interested in doing a full migration.
