### ISSUE TITLE
Stateless components do not render correctly

### ISSUE THREAD

**Issue by danpantry** [ngReact/ngReact#142]
### Issue
Stateless components do not appear to be supported. Attempting to pass a stateless component to `reactDirective` produces the following error:

> No `render` method found on the returned component instance: you may have forgotten to define `render`, returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.

### MVCE
```jsx
function Header(props) {
  return <aside>
    <h1>Hello, World!</h1>
  </aside>
}

export default Header
```

```javascript
import angular from 'angular'
import ngReact from 'ngreact'
import Header from './Header'

angular.module('app', [ngreact])
  .directive('helloHeader', reactDirective => reactDirective(Header))

angular.bootstrap(document.documentElement, ['app'])
```

```html
<html>
  <body>
    <hello-header></hello-header>
  </body>
</html>
```

### Versions
- `angular@1.2.27`
- `ngreact@^0.2.0`
- `react@^0.14.7`
- `react-dom@^0.14.7`

**Comment by danpantry** [comment]
Uh. Well, this is awkward. User error :-) was pointing at a `.ts` file instead of the correct `.tsx` file.

**Comment by kasperp** [comment]
no worries.
