### ISSUE TITLE
TypeScript and injections

### ISSUE THREAD

**Issue by Buthrakaur** [ngReact/ngReact#143]
Hello,
I'm trying to get started with ng-react and TypeScript 1.8, but I'm struggling with the component registration when I want to inject some dependencies into the React component. My current component looks like this:

```
interface Props {
    title: string;
    someService: any;
}

class HelloReactComponent extends React.Component<Props, {}> {
    render() {
        return <div>
            <span>Hello React: {this.props.title}</span>
            <span>{this.props.someService.getValue()}</span>
        </div>;
    }
}
```

Now I'm not able to use the trivial registration using `angular.module(x).value(...)`, but need to use `angular.module(x).factory(...)` and don't see any possibility how to use the `HelloReactComponent` class in this case. Do I really need to redesign my component not to be a class, but write the code in `React.createClass` without possibility to use the class?

**Comment by kasperp** [comment]
@Buthrakaur thanks for raising this. So If you use `React.createClass` there is no problem ? Could you post an example of your use of `angular.module(x).value(...)` ?

**Comment by kasperp** [comment]
Closed due to inactivity. Feel free to reopen.
