### ISSUE TITLE
How to user Date Picker component with ngReact

### ISSUE THREAD

**Issue by 3v3r3tt** [ngReact/ngReact#144]
ngReact can be utilized if _Someone in the React community released a component that you would like to try out_

I'm trying to figure out how to use [this React DatePicker](https://github.com/Hacker0x01/react-datepicker) in an ngReact component like so:

in my gulpfile.js

...
var DatePicker = require('react-datepicker');
var moment = require('moment');
...

and DateEditCmpt.jsx

![screen shot 2016-03-14 at 11 06 34 am](https://cloud.githubusercontent.com/assets/6601974/13752563/ee3e74fe-e9d4-11e5-9a4f-b5d923e81079.png)

But am getting a Reference Error:

`ReferenceError: DatePicker is not defined`

Is it possible to user community components like this with ngReact? If so what am I missing here.

**Comment by kasperp** [comment]
Should be poosible. Is the DatePicker available on the global object? 

The code you posted assumes that it is available.

**Comment by kasperp** [comment]
Closed due to inactivity. Feel free to reopen if still relevant
