### ISSUE TITLE
Nested Directives

### ISSUE THREAD

**Issue by manuschiller** [ngReact/ngReact#147]
Hi,

i tried ng-react and it works perfectly! However if I try to use nested components, it won't render the child components.

like:

```
<my-table>
  <my-tr>
    <my-td>
    </my-td>
  </my-tr>
</my-table>
```

each element is defined like (substituted MyTable for MyTr and MyTd and adjusted the element type)

```
angular.module("app")
    .value("MyTable",React.createClass( {
        propTypes: {
            table: React.PropTypes.object.isRequired
        },

        getDefaultProps: function(){
            return { table: {}};
        },

        render: function(){
            return React.createElement("table", null);
        }
    }));

angular.module("app")
    .directive( 'myTable', function(reactDirective){
        return reactDirective( 'MyTable');
    });
```

is there any workaround for that?

**Comment by kasperp** [comment]
Yeah - the work around is to create a new component which wraps the concrete children so

```javascript
angular.module("app")
    .value( "MySpecificTable", React.createClass( {

        render: function() {
            // you'll need to pass in the data that fits your domain as props and
           // iterate through that data to create your the concrete table elements
            return ( 
              <MyTable>
                 <MyTr>
                    <MyTd>
                   </MyTd>
                  </MyTr>
             </MyTable> 
           );
        }
    }));

  angular.module("app")
    .directive( 'mySpecificTable', function(reactDirective){
        return reactDirective( MySpecificTable );
    });
```

You can then use it like this 

```html
<my-specific-table .... />
```

See also #131 and #128

NOTE: I assume that you MyTable, MyTr and MyTd componets actually adds some functionality (styling or otherwise) else I would recommend that you just use `<table>`, `<tr>`, `<td>` from the specific table component

**Comment by manuschiller** [comment]
ok, thanks! just another rookie question: 
how would me file have to look like that I won't get a "unknown token < " error for the html part?

```
render: function() {
        return ( 
              <MyTable>
                 <MyTr>
                    <MyTd>
                   </MyTd>
                  </MyTr>
             </MyTable> 
           );
        }
```

**Comment by kasperp** [comment]
Yes - if you don't run a jsx transform, see https://github.com/ngReact/ngReact#jsx-transformation-in-the-browser. 

if you don't want to use jsx you need to write something like:

```javascript
return React.createElement( MyTable, null, React.createElement( MyTr, null, ...);
```
