### ISSUE TITLE
watch-depth in reactDirective ??

### ISSUE THREAD

**Issue by bdkent** [ngReact/ngReact#150]
Is it possible to provide a `watch-depth` value for _all_ instances of a component defined via `reactDirective(...)`? 

All the examples I see provide `watch-depth` at each usage in the HTML.

I want to provide it only once during the `reactDirective` creation instead of at each usage. Is that possible?

**Comment by kasperp** [comment]
@bdkent thanks for your issue. No that isn't possible at this time.

**Comment by bdkent** [comment]
Is it something you could support in a future release?

**Comment by kasperp** [comment]
@bdkent sure - there is some overlap with #155, is it something you would like to take a stab at ?
