### ISSUE TITLE
Customise what values are watched?

### ISSUE THREAD

**Issue by jamesmorgan** [ngReact/ngReact#155]
I am currently in the process of splitting a large slow angular JS v1 table to a few react components with the idea of improving performance. 

When I create the component I provide a set of props such as this:

``` javascript
offerData = {
    day: day,
    availability: availability[date],
    disabledIndex: vm.disabledIndex,
    $index: $index,
    setCloseOutItem: vm.setCloseOutItem
}
```

``` javascript
<react-component name="OfferCell" props="offerData" watch-depth="reference"></react-component>
```

It works like a charm however in order for the component to react to changes made in one of the properties I need to changed `watch-depth="reference"` to `watch-depth="value"`, this then has a performance impact and it appears to render the page almost unusable with the page running at 100% cpu like its stuck in a loop. 

Of the several things I pass in I only really need to component to re-`render()' on a small subset of properties.

Is there a way of defining what props are watched or is there any other way of providing differing attributes from props which are then accessible in the react component?

Maybe I am getting the wrong end of the stick with this as I am no react expert.

I have played around with `ngReact` source and changed the props attribute to something such as `watchProps` and then changed the source to use this instead, it works but this feels wrong and I am hoping there is anything way. 

``` javascript
   // Notice the use of watchProps instead of props here..! <<
attrs.props ? watchProps(attrs.watchDepth, scope, [attrs.watchProps], renderMyComponent) : renderMyComponent();
```

Does anyone have any ideas?

**Comment by kasperp** [comment]
@jamesmorgan sorry for not getting back to you earlier.

There is currently not a way to customize which properties have which watch depth. Though I think it is a good idea. 

Is it something you would be interested in giving a attempt to implement? There could be potential for solving this and #129 with type of design.
