### ISSUE TITLE
The Unknown provider error not displayed when using directive in minified code

### ISSUE THREAD

**Issue by mattburrell** [ngReact/ngReact#156]
According to the [readme](https://github.com/ngReact/ngReact/blob/master/README.md#minification) guide the following error should be displayed when using a directive in minified code and an annotation library and the directive lacks an explicit `$inject` statement, e.g.:

`Unknown provider: eProvider <- e <- helloDirective`

This error message was not displayed in my case. Instead I received the `Cannot find react component...` message.

The error was swallowed up by the `catch` clause on line number [49](https://github.com/ngReact/ngReact/blob/master/ngReact.js#L49)

A `console.log( e )` revealed the ``Unknown provider: eProvider <- e <- helloDirective` error and an explicit `directive.$inject` fixed the issue.

Should the error have been thrown at line 49 rather than ignored?

**Comment by kasperp** [comment]
Thanks for reporting this, that is certainly a inconsistent between the code and the readme.

What would be your suggestion: change the readme to match the code or change the code to match

You could argue that "Cannot find react component" is a better error message. Of cause it could be a lot better and at give you the hint about missing an $inject - that currently is in the readme..

**Comment by mattburrell** [comment]
The "Unknown provider..." message was more helpful to me because the "Cannot find react component" message actually referred to a parent component. :)

Some sort of hint about the missing $inject would be useful I think.

**Comment by bdkent** [comment]
Any chance of this being fixed??
