### ISSUE TITLE
onTouchTap events of material-ui buttons are not working

### ISSUE THREAD

**Issue by rdkrish** [ngReact/ngReact#157]
We are in a transition phase trying to move few modules of our angular app to react components. In our React components we heavily use [material-ui](http://www.material-ui.com/) components.

As suggested in the [installation](http://www.material-ui.com/#/get-started/installation) page of material-ui, we are using [react-tap-event-plugin](https://github.com/zilverline/react-tap-event-plugin) library to enable onTouchTap events of material-ui buttons.

If I render the independent React component in a browser, onTouchTap events work perfectly! But the same component, if I embed in the angular app using ngReact, component rendering is fine, but events are not getting fired.

Any help would be deeply appreciated!

Thanks in advance!

**Comment by kasperp** [comment]
Thanks for raising this. 

Have you done any investigation why they events don't get fired? I'm sorry that I can't offer you any insights here.

**Comment by oliviertassinari** [comment]
This callback was removed from Material-UI, we can know close the issue.
