### ISSUE TITLE
Export the module name

### ISSUE THREAD

**Issue by mohsen1** [ngReact/ngReact#158]
When using ng-react with CommonJS `require` statements it's not possible to retrieve the AngularJS module name from the module. 

Most AngularJS modules published to npm export the module name string value so they can be used like following [example](https://www.npmjs.com/package/angular-resource): 

```js
angular.module('myApp', [require('angular-resource')]);
```

**Comment by Kepro** [comment]
this is not a problem with ngReact...

**Comment by mohsen1** [comment]
If I require mgreact in a commonjs environment it doesn't return the module name

**Comment by kasperp** [comment]
@mohsen1 thanks for the issue. Right now we return the module it self and you need to type name name of the module your self. 

Would it be a better option to return the name instead ?

**Comment by mohsen1** [comment]
Yes. Angular core modules do this. They return the name so you can directly require it in the dependency lost of the app. See my original post example of Angular resource

**Comment by kasperp** [comment]
This is be a breaking change to ngReact (a small one, but still breaking), so I'm not sure this small nicety is worth breaking over.
