### ISSUE TITLE
force update react component

### ISSUE THREAD

**Issue by Kepro** [ngReact/ngReact#159]
is there a way how to force update a props in react from angular? because if object lost reference then doesn't update react from angular

**Comment by kasperp** [comment]
Hi @Kepro thanks for you question. 

How do you mean "lost reference" ?

**Comment by Kepro** [comment]
hi @kasperp, i have a 
```$scope.reactProps = {
 code: code,
 value: value,
 prefix: prefix,
};```

after service update from service, i update a $scope.reactProps.value = newValue;
then react doesn't get any update in it, if i tried any watch property :/

**Comment by Kepro** [comment]
uhm... my fault... i play wrong with shouldComponentUpdate
