### ISSUE TITLE
Performance Killing

### ISSUE THREAD

**Issue by Attrash-Islam** [ngReact/ngReact#161]
Hi,
I've used angularjs for the past four years and I've started to enter the world of reactjs.
Entering and merging some reactjs components was for the benefit of it's performance, but the basic of ngReact and all the reactjs components out there is to "$watch" the props to update the state is really a bad idea. It's the same ngStyle, so why we need reactjs so more?

Finally I've used $rootScope.$emit and to listened by $rootScope.$on for an event with the component name, and this flag will till the reactjs component to render the view (data for rendering will be passed through the event)

I know that is Flux, but with using $$watcher we're failing into the same performance issues that we're escaping from!

Thanks for your efforts

**Comment by Attrash-Islam** [comment]
I also tried that over huge set of data, and the differences is so HUGE also

**Comment by kasperp** [comment]
@Attrash-Islam thanks for filling this issue. Performance is obvious one of the reasons people look at something like ngReact, so anything that can make the better is interesting. 

Could you share some code and results that better illustrates what you are suggesting and benefits it would give?

**Comment by Attrash-Islam** [comment]
@kasperp Thanks for the replay. Well, I was working with more than 2000 objects, each object contain some properties that will be rendered in the view as a table.

When I wrapped my reactjs component with a angularjs directive that $watches the props and then calling this.setState to update the rendered big table I was forced to use:

scope.$watch('myBigList', () => {}, **true**) because maybe some sort of inner value will be changed, so now I'm $watching a huge list with more than 2000 objects, each object contains no less than 10 attributes! other than the other attributes (props) that are representing some objects and arrays also!

Basically, there's two ways to bypass this case:
1) using immutable data, and the $watch will do === equality which will take O(1)
http://blog.mgechev.com/2015/03/02/immutability-in-angularjs-immutablejs/

2) using events that trigger in the places which the data changes, and to make some kind of mechanism to deal with that inside the angularjs directive.

Those two ways are meant to skip the whole nonperformance $watch functionality, and with using that we're not solving the ngPerformance at all

Results: I saw through ng-stats that my $watchers count where not increasing even when scrolling in this infinite scroll big table, because all the view is rendered with reactjs, BUT the page started to lag, and I saw that the digest cycle (not the $$watchers number) started to reach big number! And when replaced this pattern with some event triggering where the change is made for the array, the page working well.

I believe that you can offer some another ideas for telling the angularjs directive to render without using $watch, which falls you back to the angular bad performance.

Best Regards

**Comment by Attrash-Islam** [comment]
One idea I really don't sure about is using .component API with $onChanges, I really don't know, but I guess that this is not a regular $watcher.. Maybe I don't know

**Comment by Attrash-Islam** [comment]
I really used .component API it's rock!!!!!!!!! replacing the $watch with using the $onChanges! It's working very great!

**Comment by kasperp** [comment]
@Attrash-Islam thanks again for you insight. 

Could you perhaps share some code that runs and shows the speedup ?

**Comment by Attrash-Islam** [comment]
Yes Sir, and I'll make for you a good report for this :)

**Comment by Attrash-Islam** [comment]
I've the example working very good!!
I'll upload it with a video tonight..
and I'll share it, so we can think of upgrading ngReact to use $onChanges for performance boost with big differences!

**Comment by Attrash-Islam** [comment]
Here's the video:

https://youtu.be/GzFC-mwsygA

**Comment by kasperp** [comment]
Thanks for that, however I still don't understand what you are proposing and how your video relates to ngReact. I'm sure you have point, I just have are hard time understanding.

Perhaps it would help me if you could try to answer these questions: 

* Which part of ngReact so you experience perf issues, initial setup, watches while app is running, etc ?
* How do you propose to fix it with $onChanges ? 
* Will your proposed change break other aspects of ngReact ?
* What are the performance gains you have experiences. Please try to be precise here. Measure before and after and show the numbers
* Please suggest concrete changes in ngReact, perhaps with a pull request, that illustrates your point.

**Comment by Attrash-Islam** [comment]
Hey there,
Thanks for giving my video your time.

1- The performance is related to the prop $watchers, which basically so heavy when we're targeting huge arrays that have complex objects to deeply watch, and that common in big projects

2- I think that the idea is to change the directive and to use .component API in the sake of using $onChanges and that's not a big deal because you're already linking to the last stable angular.js which contains that API

3- I really don't know, I must give a try to change a little bit, without changing a lot, but I guess that the change will be related to reactComponent to be rewritten to work as Component (I'll try a pull-request)

4- The gains is related to faster digest cycle while app is running, you can see that when we are deeply $watching the changes we're receiving 5.09 in the ng-stats digest cycle time taken to finish the dirty checking, and that is because we're linking with this additional $watcher a huge huge object list! and when using the same data with $onChanges API (With the need sometime to clone) made our digest cycle faster 5X, where we can see clearly that the time is not reaching 1.00 !

5- I'll try my best in the pull request with adding the example with the huge JSON data

Thanks

**Comment by Attrash-Islam** [comment]
After reading the source code fair enough I can see that ngReact is really a great library.
You can have this as a note in your documentation which encourages users to angular.copy their props every time there's a change, specially when the props are complex big data, and to change the watch-depth to reference.

But that you can reach the same performance values, but I didn't so this performance tip in the documentation and thought that this implementation is missed

I've already removed my video
I hope you can add this note in the README

Thanks :)

**Comment by kasperp** [comment]
@Attrash-Islam :+1: thanks sounds like a good idea to add a note in the README.

**Comment by josivan** [comment]
@Attrash-Islam I'm trying to watch the video, but the link [https://youtu.be/GzFC-mwsygA](https://youtu.be/GzFC-mwsygA) is not working.

**Comment by Attrash-Islam** [comment]
@josivan I already sent to you a replay in the mail. Unfortunately, the video has been removed a while ago
