### ISSUE TITLE
Component Names in react-dev-tools & missing prop warnings

### ISSUE THREAD

**Issue by seanlindo** [ngReact/ngReact#165]
Hey all,

I seem to be getting a component name of `t` in react dev tools (I expected it to be `Hello`). Any idea why this might be? Here's some factory code!

```
/**
 * Displays 'Hello' and the props in a concatenanted string
 */
angular.module('core').directive('hello', function (reactDirective) {
    var Hello = React.createClass({
        propTypes: {
            fname: React.PropTypes.string.isRequired,
            lname: React.PropTypes.string.isRequired
        },

        render: function () {
            return React.DOM.span(null,
                'Hello ' + this.props.fname + ' ' + this.props.lname
            );
        }
    });

    return reactDirective(Hello);
});
```

The above is used as `<hello fname="ctrl.fname" lname="ctrl.lname"/>`

As an aside, I don't seem to be generated any warnings in the console when leaving off props.

**Comment by kasperp** [comment]
@seanlindo thanks for raising this. When I open the example page http://ngreact.github.io/ngReact/examples/hello/ with chrome dev tools, I see this:

![screen shot 2016-09-09 at 23 19 50](https://cloud.githubusercontent.com/assets/481303/18403319/4f0d849a-76e4-11e6-8655-0cfcbd718890.png)

So the components are called <Constructor/> not <Hello/> is that what you are seeing ?

**Comment by seanlindo** [comment]
Yours definitely looks more correct! Give me until EOD today (9/12) and I'll corroborate
