### ISSUE TITLE
Example of using ngReact with a third-party React component

### ISSUE THREAD

**Issue by 3dg4r** [ngReact/ngReact#168]
I'm trying to use ngReact to implement the Airbnb react-dates calendar, and so far my only successes have been getting the component to render on the page via reactDirective, and then being able to set initial prop values and receiving events from the component. Beyond that, it's difficult, for me at least, to understand how to trigger the component to render with the new state, since all of the examples I can find involve components that are 100% dictated in the Angular app. An example of using ngReact with a third-party, npm-linked component would be very helpful.

**Comment by kasperp** [comment]
@3dg4r your that that would be good with an example that better illustrated how to  use a third-party component.

Any help with that would be great.

**Comment by aviadhahami** [comment]
@3dg4r Hey, I've just implemented [airbnb's react-date](https://github.com/airbnb/react-dates) using _ngReact_.
Was relatively fine, but I did feel like I was creating an abomination 😥 .
About your question, we need to differ between two cases:
1. Changes within the React component itself
1. Changes within the containing Angular app

When we're using this component (the date picker) we need to understand that _it has its own state_ (it's not a stateless component), therefor whenever we perform a change of the component's state (i.e. change date) the date picker will render itself without "notifying" angular (you can check it with ease, add a `console.log` to the head of the render function) . This is the first case.

The second case is a change originated in the containing app.
Assuming we have some object in the controller (`$scope.myObj = {a:1}`) that we pass as props to our component `<react-component name="myComp" props="$ctrl.myObj">` angular should update every DOM element that uses `$ctrl.myObj`.
**However**, this doesn't work for `react-component` (at-least not for me) so an easy solution was to wrap the component with an `ng-if`, and whenever there's an update toggle the boolean value for the if.
Yes, it is ugly but it work. For me it's not an issue as I've got a loading screen covering my whole view on each update thus there's no "blink" of the react component.

**Comment by g3hk** [comment]
Have you implemented a third party reusable component with ngReact? if so can you share it with me

**Comment by g3hk** [comment]
Do you have any example of using 3rd party react components published in npm ???? i too need it urgently kindly share it please

**Comment by g3hk** [comment]
i want to use that 3rd party component with ngReact in angular 1.6.x
