### ISSUE TITLE
JSX issue

### ISSUE THREAD

**Issue by PVAngular** [ngReact/ngReact#169]
I have a non-SPA page with angular. I am trying to migrate some of the controllers React. I followed ngreact approach and was able to render a simple "hello" as long as I use ES5 javascript and no JSX.
 I am struggling to determine what libraries convert react components JSX to JS. I dont use webpack. Which babel files I need to add as <script src=""> files for this to work? Please help..

**Comment by kasperp** [comment]
@PVAngular you want to use the react preset to transpile jsx to js https://babeljs.io/docs/plugins/preset-react/

**Comment by PVAngular** [comment]
Thanks for the reply. I am using webpack to transpile JSX to js. However, the final "index.js" created by webpack creates React components as local variables(scoped in functions) and so they are not available to Angular. I am currently using Angular 1.4. Any suggestions on how to expose those react components globally? Thanks.

**Comment by kasperp** [comment]
You can use the webpack expose loader - https://github.com/webpack/expose-loader

**Comment by PVAngular** [comment]
I used this but I dont see any change in the generated webpack file. Hence, I am still not able to expose the React components and I get "cannot find react component error". Has anybody used Angular with React(ES6) and then used expose-loader with webpack?
