### ISSUE TITLE
react component does not show in all browsers

### ISSUE THREAD

**Issue by wrjanan** [ngReact/ngReact#170]
The react-component directive that I am using shows on more updated browsers, though they do not show on less updated browsers.

It feels like if I delve a little deeper into babel compilation might lead me closer to ensuring the react component works with less updated browsers.

Currently, the react-component directive is stored in item.directive.js

```
'use strict';

var ReactItem = React.createClass({..});

angular.module('SqkiiApp').value('ReactItem', ReactItem);
```

Also, using grunt to manage the compilation process.

Is there a resource that works with ngReact to allow the react-component directive to work across most browsers?

**Comment by kasperp** [comment]
@wrjanan which browsers are you targeting ?
