### ISSUE TITLE
Props not passed to stateless components 

### ISSUE THREAD

**Issue by pawelpabich** [ngReact/ngReact#172]
Hi,

First of all, great project. 

I'm using ngRect with regular React components and it works great. I noticed that most of my components are basically pure functions and tried to convert them to stateless components which doesn't seem to be supported. This [issue](https://github.com/ngReact/ngReact/issues/142) indicates that it should.

I cloned this repo and then replaced the Hello component in hello example with its stateless counterpart:

```
function Hello(props) {
    return React.DOM.span( null,
      'Hello ' + props.fname + ' ' + props.lname
    );
};
```

When I did that then the `Hello` component is called with empty props. The interesting thing is that `<react-component` syntax works just fine. 
![image](https://cloud.githubusercontent.com/assets/347637/19102413/6b8dd10e-8b13-11e6-8a00-779f360a2b73.png)

**Comment by kasperp** [comment]
@pawelpabich thanks for reporting this. Did you add `PropTypes` to the component? 

From the README:

> The reactDirective service will read the React component propTypes and watch attributes with these names. If your react component doesn't have propTypes defined you can pass in an array of attribute names to watch.

**Comment by pawelpabich** [comment]
Yep, that was it. User error :). 
This fixed it:  
```
Hello.propTypes = {
  fname: React.PropTypes.string,
  lname: React.PropTypes.string
};
```
