### ISSUE TITLE
React Component Won't Recognize Props

### ISSUE THREAD

**Issue by shadow1349** [ngReact/ngReact#174]
Can someone please answer this question?

http://stackoverflow.com/questions/40181866/using-ngreact-with-asp-net-mvc

I have tried to copy and paste the code over from the example, but nothing seems to work.

What am I doing wrong?

Thanks!

**Comment by shadow1349** [comment]
I answered my own question, checkout the link in my first post to see the answer!

**Comment by kasperp** [comment]
@shadow1349 thanks for the question. Since you answered it I'll close the issue.

**Comment by ebuildy** [comment]
You answered your own question and +1 your own issue and comment , hmmm, you may need something else than github to help you ^^
