### ISSUE TITLE
How to make React directive disappear from the DOM?

### ISSUE THREAD

**Issue by pawelpabich** [ngReact/ngReact#177]
Hi,

More than likely this is me not fully understanding how the bridge works but is there a way to remove the React component (e.g. `hello` tag in the examples) from the DOM? 

Why do I need that? I have a component that uses Bootstrap 3 grid and some of the Bootstrap classes use `%` for widths. This doesn't work when the immediate parent of an element is no the real parent, eg. `ul -> my-react-component->li`

![image](https://cloud.githubusercontent.com/assets/347637/20507776/a6928e24-b0a8-11e6-9b0f-9249b8f392ec.png)

**Comment by kasperp** [comment]
You should be able to change the configuration of the generated angular directive, see https://github.com/ngReact/ngReact#the-reactdirective-service (last paragraph).

Then I guess you can set the [replace option](https://docs.angularjs.org/api/ng/service/$compile#-replace-deprecated-will-be-removed-in-next-major-release-i-e-v2-0-)

**Comment by aabenoja** [comment]
Unfortunately not much to be done around this. In order for `replace: true` to kick in, which is [on by default](https://github.com/ngReact/ngReact/blob/bc59f466439e8644f4168a5643c78dd7ee4c1251/ngReact.js#L151), you need to provide a `template` or `templateUrl` value. However, all that will do is change that `<hello>` tag with all those attributes into a different element you specify in your template.

To achieve that dream of killing that fairly unnecessary container will require a bit more thought, and I'm not entirely sure how to achieve this through angular.
