### ISSUE TITLE
It is possible to use production build react version rather than development version

### ISSUE THREAD

**Issue by ronilitman** [ngReact/ngReact#180]
Hi,

I have successfully implemented react inside angular project, and it looks great.

I have encountered a minor issue though. When I deploy my code to production environment, I am getting warning message from react: 

> It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster.

Is there a way that I can really use the production build of react in order to avoid this warning message?

If it matters, I use grunt-babel with es2015 presets + transform-react-jsx plugin.

Thanks!

**Comment by sudheerDev** [comment]
I have override for this in wiredep task of my gruntfile.js

          overrides: {
          'react': {
            main:  [
              'react.min.js',
              'react-dom.min.js'
            ]
          }
       }
