### ISSUE TITLE
babel-loader @jsx React.DOM pragma deprecated

### ISSUE THREAD

**Issue by cwmoo740** [ngReact/ngReact#183]
Upgrading to webpack 2.2 and using babel-loader with the react preset throws an error:

`ERROR Module build failed: SyntaxError: The @jsx React.DOM pragma has been deprecated as of React 0.12`

**Comment by cwmoo740** [comment]
I see that this was fixed with 

https://github.com/ngReact/ngReact/commit/bc59f466439e8644f4168a5643c78dd7ee4c1251

There should be a patch release of 3.0.1 including this commit.

**Comment by rafarovina** [comment]
Hi @cwmoo740, I had the same problem and soved it by adding the following line to my _.babelrc_
`"ignore": ["*ngReact.js"]`

**Comment by kasperp** [comment]
Thanks I'll see about making new patch release - will not be for the next couple of weeks though.

**Comment by kasperp** [comment]
Fixed in 0.4.0
