### ISSUE TITLE
More modern alternative to ngReact

### ISSUE THREAD

**Issue by bcherny** [ngReact/ngReact#186]
I'm not sure an issue is the right place to put this, but we've had a lot of success using ngimport with react2angular as an alternative to ngReact, to overcome some of ngReact's limitations and have a more friendly API:

- ngimport: https://github.com/bcherny/ngimport
- react2angular: https://github.com/coatue/react2angular

I'm curious what the ngReact maintainers think.

**Comment by kasperp** [comment]
@bcherny those libraries look great and you're right they seem like a modern alternative. To be honest the there hasn't been a lot of development here in a while, and we seem to lost momentum. I'm happy to see that there are alternatives that can help bridging these technologies. 

I think it we could add those to the README as alternatives if your looking for something more modern. If you want to open a pull request with that it would be welcome.

Thanks for posting.

**Comment by bcherny** [comment]
@kasperp Yeah, that was much hunch too - thanks for the quick response.

Where in the README do you think is a good place for it?

**Comment by kasperp** [comment]
Maybe right at the top 😄

**Comment by bcherny** [comment]
Done! https://github.com/ngReact/ngReact/pull/187

**Comment by kasperp** [comment]
thanks
