### ISSUE TITLE
Module react is not available 

### ISSUE THREAD

**Issue by msamusammil** [ngReact/ngReact#195]
I am running a angular JS application. In that I am trying to add the react library in the app.module and getting the below error "Uncaught Error: [$injector:modulerr] Failed to instantiate module <mymodule> due to:
Error: [$injector:modulerr] Failed to instantiate module react due to:
Error: [$injector:nomod] Module 'react' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument."

**Comment by kasperp** [comment]
Did you add react as a module in your angular app, see Usage section in [README](https://github.com/ngReact/ngReact#usage)?
