### ISSUE TITLE
react/react.js and react-dom.js are missing from bower folder

### ISSUE THREAD

**Issue by kkbrains** [ngReact/ngReact#203]
I have included ngReact using bower and the following files are missing under bower_components/react/ folder

```
bower_components/react/react.js
bower_components/react/react-dom.js

```

The latest version v16.0.0 of https://github.com/reactjs/react-bower has remove those files from source location.

Modifying the bower.json 
`react: "~15"`
would fix the issue

**Comment by kasperp** [comment]
Thanks. Should be fixed now.
