### ISSUE TITLE
How to fix these warnings

### ISSUE THREAD

**Issue by jithureddy** [ngReact/ngReact#206]
I am getting warnings when I use ngReact in angualr js app. Please help how to fix this my directive looks like below.
(function () {
    'use strict';
    var GreetingSection = React.createClass({
        displayName: 'Greeting',
        propTypes: {
            name: React.PropTypes.string
        },
        render: function () {
            var message = "Good morning " + this.props.name + ", how are you?";
            return React.createElement('div', { className: "greeting" }, message);
        }
    });

    angular
        .module('app.components.work')
        .directive('reactComponentOne', reactComponent1);
    /** @ngInject */
    function reactComponent1(reactDirective) {
        return reactDirective(GreetingSection);
    }
})();

![image](https://user-images.githubusercontent.com/5911189/33619863-445d8a72-da0c-11e7-9b87-8e226c37fed5.png)

**Comment by maddrag0n** [comment]
You are using the deprecated ES5 syntax. This is a deprecation warning from React 16 and has nothing to do with ngReact.

```js
class GreetingSection extends React.PureComponent {
  static displayName = 'Greeting'

  static propTypes = {
  name: React.PropTypes.string
  }

  render() {
    const message = `Good morning ${this.props.name}, how are you?`;
    return React.createElement('div', { className: "greeting" }, message);
  }
}
```
