### ISSUE TITLE
JSXTransformer is not present in bower components after installing ngReact

### ISSUE THREAD

**Issue by jithureddy** [ngReact/ngReact#207]
How can we execute JSX code as shown in examples. When I tried to use jsx files, I cannot see the transformer js which should run before angular app bootstrap. Please see the below screen shot for reference.
I am trying to use this example : - https://github.com/ngReact/ngReact/tree/master/examples/jsx-transformer 
![image](https://user-images.githubusercontent.com/5911189/33702959-e078d6a6-db4b-11e7-8165-7848bf797982.png)
Please I need help to use react in angularjs es5 project setup

**Comment by daru23** [comment]
I am having the same issue. Not success yet. :(

**Comment by AdityaParameshwara** [comment]
Same issue!

**Comment by AdityaParameshwara** [comment]
Solved this issue:
Include <script src="https://unpkg.com/react@0.12.0/dist/JSXTransformer.js"></script>
in your html head and make sure you load your jsx file before the app.js file. It worked for me.
