### ISSUE TITLE
How to use a static value as props?

### ISSUE THREAD

**Issue by ebuildy** [ngReact/ngReact#209]
I can easily use angular controller variable as React component prop:

`<tabs-menu selected="tab" watch-depth="value" />`

`... $scope.tab = 'watchers'; ...`

But didnt find how to simplify like this:

`<tabs-menu selected="watchers"  />`

?

**Comment by tjefferson08** [comment]
This worked for me:
`<tabs-menu selected="'watchers'" />`

Quotes inside quotes! `"'watchers'"`
