### ISSUE TITLE
property name case matters (in html template)

### ISSUE THREAD

**Issue by maddrag0n** [ngReact/ngReact#213]
When using reactDirective, the property name case actually decides whether the component will update for watched scope.

```html
<my-component
  prop-that-will-be-updated="propThatWillBeUpdated"
  propWithStaticValue="propWithStaticValue" />
```

```js
// my-component.directive.js
import React from 'react';

const MyComponent = (props) => {
	console.info('rendering MyComponent', { props });
	return <span>MyComponent</span>;
};

const MyComponentDirective = reactDirective => reactDirective(MyComponent, [
	'propThatWillBeUpdated',
	'propWithStaticValue',
]);
MyComponentDirective.$inject = [ 'reactDirective' ];

export default MyComponentDirective;
```

In that example mutating `$scope.propThatWillBeUpdated` will trigger a render cycle for MyComponent, but mutating `$scope.propWithStaticValue` will not. Both props will be populated when MyComponent is mounted.

If that is expected behavior, I could not find any documentation that indicates that (tho I might be stupid and blind).

**Comment by paulsc** [comment]
+1 

I just encountered the same behavior and it took me a while to figure out why my component wasn't updating when the prop changed. Turns out changing the prop name to lowercase fixed it.

**Comment by wezleytsai** [comment]
Wow! Took me a long time to realize this was the root cause of my bug.
