### ISSUE TITLE
Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by namanb95** [ngReact/ngReact#223]
`angular.js:15567 TypeError: Cannot read property 'render' of undefined
    at ngReact.min.js:1
    at Scope.$digest (angular.js:19112)
    at Scope.$apply (angular.js:19500)
    at done (angular.js:13343)
    at completeRequest (angular.js:13600)
    at XMLHttpRequest.requestLoaded (angular.js:13505)`

Getting this issue.

react component Written as : 
`var auth = angular.module('auth');

/** @jsx React.DOM */
let React = require("react");
let createClass = require('create-react-class');

auth.value('Hello', createClass({
    render: function() {
        return <div>Hello {this.props.name}</div>;
    }
}));
auth.directive('hello', function(reactDirective) {
  return reactDirective('Hello', ['name']);
});`

And implemented in dashboard.html as 
`<hello watch-depth="reference" ></hello>`

**Comment by Sark91** [comment]
Hey, I hope that you resolved your issue. I had the same issue and I found that React and ReactDOM have to be initialised (and maybe assigned into the window variables) before the ngReact. At least it helped me.
