### ISSUE TITLE
React Object component support

### ISSUE THREAD

**Issue by porluz** [ngReact/ngReact#224]
Seeing the error "cannot find component" when using React object components (React.memo, etc). Will this be updated to support React 16.8?

**Comment by kasperp** [comment]
Thanks for you request. I doubt ngReact will get updated and I suggest you look at some alternatives like 

https://github.com/microsoft/angular-react or https://github.com/coatue-oss/react2angular

**Comment by porluz** [comment]
ok, seems to work when I allow functions as well as objects where the name is checked and the error is generated. Will go with that. Thank you.
