### ISSUE TITLE
this.props.data undefined in ReactComponent

### ISSUE THREAD

**Issue by tihomir-kit** [ngReact/ngReact#4]
Hi,

I'm invoking the directive like this:

``` html
<div ng-react-component="ReactList" data="myItems"></div>
```

which is the recommended way on [docs page](http://davidchang.github.io/ngReact/).

This is what my ReactComponent code looks like:

``` javascript
window.ReactList = React.createClass({
    render: function() {
        // this.props.data is undefined here
        // this.props.scope.data is undefined here
        // this.props.scope.myItems is a valid collection of items here

        return (
            <ReactListBase scope={this.props.scope} items={this.props.scope.myItems } />
        );
});
```

the problem is that `this.props.scope.data` is undefined within the React component and if I understand this correctly, it should contain `myItems`?

Is this a bug or am I doing something wrong here?

**I'm using:**
AngularJS v1.2.14
[Latest ngReact](https://github.com/davidchang/ngReact/blob/b61e2591dd1159b1c991126b911787316f0a9077/ngReact.js)
ReactJS v0.10.0

Thank you

**Comment by cloudybrain** [comment]
you can try data-data, I think the data-attribute built into html might have interfered with this.. this problem happened with me since I had a prop called "dataSet", and to fix this, I had to use data-data-set

**Comment by ddaaggeett** [comment]
@pootzko 

> We implemented a workaround for this which works fine

can you share this here?
