### ISSUE TITLE
React ref not working

### ISSUE THREAD

**Issue by bl4ckbon3** [ngReact/ngReact#67]
For example

```javascript
render() {
 return <div ref="sample"></div>
}
```

will cause exception
> Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

**Comment by kasperp** [comment]
@bl4ckbon3 thanks for you issue. Just so I understand the problem, you get this error if you add a ref to a component that you want to use with `react-component` ?

**Comment by bl4ckbon3** [comment]
@kasperp yes...when i use react component with ref, I got that error

**Comment by kasperp** [comment]
@bl4ckbon3 I tried to replicate the issue in the hello world sample [here](https://github.com/davidchang/ngReact/commit/19689ebcb47f5949a924fab55f0e27fe3ed246c7). 

But it seems to work for me. Could you perhaps provide an similar example that fails, thanks.

**Comment by bl4ckbon3** [comment]
Dear, i know the problem. I use ngreact and react from different repository

**Comment by kasperp** [comment]
@bl4ckbon3 hmm that does sound strange. Do you have any more information you can share ?

**Comment by eliseumds** [comment]
Crap, I was doing exactly the same thing haha

I have an Angular that loads modules from Bower and I use WebPack to compile my React-related stuff, that was loading React again from NPM.

**Comment by arnars** [comment]
I have the exact same problem. Does not matter which react version/file I require in my component file.

In the below the `ref="listTable" gives the error described above. There are very little on google on this matter, and the error message itself is not very helpful, as it is simply not relevant. :-(

```
		return (
			<table className="c-smart-table__table" ref="listTable">
				<thead>
					<tr>
						{Headers}
					</tr>
				</thead>
				<tbody>
					{Rows}
				</tbody>
			</table>
		);
```

**Comment by arnars** [comment]
I think this should be opened again. I get this error every time I try to use a 3rd party component that holds its own reference to React and therefore introducing a different version of the react source. 

Currently trying to use http://hacker0x01.github.io/react-datepicker/ which fails due to the refs

**Comment by kasperp** [comment]
@arnars I reopened the issue, any suggestions about how ngReact should handle this problem better?

**Comment by arnars** [comment]
Hi @kasperp and thanks for the nice react wrapper to you and your team.

As far as I can see in the (mega)thread which I'm linking to above, is that npm 3 (probably) will solve it, as it should be easier to only have 1 version of each npm module (and not nested and nested as we know it today).

If you want to fix it in the current version you could either have react as a peerDependency (haven't tested, but in theory...) 

OR 

you could advise people using Browserify et al to do like me - make sure to reference ONE react module globally, which should be in the root of node_modules. I think this will work as long as the 3rd party components uses peerDependency.

But I don't think there is any perfect solution, as this is obviously something with React, and how it handles references internally. Anyway, I think we have not provided enough info for anybody finding this issue, to be able to solve it or at least pointed them in the right direction.

Let's hope NPM3 will make it go away for real! :-)

**Comment by kasperp** [comment]
thanks - yeah I guess a note in the README would be a helpful :smile:

**Comment by aabenoja** [comment]
At this point I don't see a reason why `angular`, `react` and `react-dom` should not be peer dependencies for this project. At the very least `angular` and `react` should be actively used in the user-defined modules. `npm@3` will certainly resolve all these issues for us with the tree flattening, thought I would much rather not rely on magic.

**Comment by kasperp** [comment]
Yeah I think you're right.
