### ISSUE TITLE
Add example for interacting with react inputs

### ISSUE THREAD

**Issue by joevandyk** [ngReact/ngReact#71]
I have an angularjs application that needs to use a reactjs component. The component contains a few input and select elements. When the inputs change, angularjs should be notified about that somehow (via events, callback functions, or something else). I'd want a function on the $scope called, or the model updated, or something.

I think this is a fairly common use case, but I couldn't find any documented/blessed way of doing so with this library.

**Comment by kasperp** [comment]
@joevandyk thanks for you issue. You are right we need to a example that illustrates how to "get data back to angular". Until we have that please see my comment here https://github.com/davidchang/ngReact/pull/11#issuecomment-60485903 for the approach that I have taken.
